# Generated by Django 2.2.11 on 2020-03-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200309_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imagef',
            new_name='image',
        ),
    ]
