# Generated by Django 2.2.11 on 2020-03-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pubdate', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/blog/')),
                ('body', models.CharField(max_length=2000)),
            ],
        ),
    ]
